export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Experience} from './Experience'
export { default as Nav } from './Nav'
export { default as Skills } from './Skills'